force_scrape: false
armor_csv: data/all_pieces.csv
weapons_csv: data/all_weapons.csv
mat_aliases:
  Smouldering Embers: Smoldering Embers
  Petrified Bones: Petrified Bone
  Whispering Slabs: Whispering Slab
  Asgardian Ingots: Asgardian Ingot
  Dwaren Steel: Dwarven Steel
  s Broken Cuirass: Lunda's Broken Cuirass
  s Broken Bracers: Lunda's Broken Bracers
  s Broken Belt: Lunda's Broken Belt
chest_pieces:
- name: Berserker Cuirass
  level: 5.0
  craft: true
  locked: false
- name: Breastplate of Guiding Light
  level: 5.0
  craft: true
  locked: false
- name: Cloak of the Black Bear
  level: 1.0
  craft: true
  locked: false
- name: Cuirass of Ares
  level: 7.0
  craft: true
  locked: false
- name: Cuirass of Raven Tears
  level: 3.0
  craft: true
  locked: false
- name: Cuirass of Zeus
  level: 10.0
  craft: true
  locked: false
- name: Darkdale Plackart
  level: 1.0
  craft: true
  locked: false
- name: Dragon Scaled Breastplate
  level: 6.0
  craft: true
  locked: false
- name: Fate Breaker Shoulder Guard
  level: 6.0
  craft: true
  locked: false
- name: Fortified Husk Cuirass
  level: 1.0
  craft: true
  locked: false
- name: Giptumadr's Breastplate
  level: 5.0
  craft: true
  locked: false
- name: Glory of Sparta
  level: 9.1
  craft: true
  locked: false
- name: Hunter's Pauldron
  level: 6.0
  craft: true
  locked: false
- name: Lunda's Lost Cuirass
  level: 5.0
  craft: true
  locked: false
- name: Mani's Pauldron of Wisdom
  level: 5.0
  craft: true
  locked: false
- name: Nidavellir's Finest Plackart
  level: 2.0
  craft: true
  locked: false
- name: Plackart of Fallen Stars
  level: 6.0
  craft: true
  locked: false
- name: Risen Snow Breastplate
  level: 1.0
  craft: true
  locked: false
- name: Shoulder Guard of Survival
  level: 1.0
  craft: true
  locked: false
- name: Shoulder Guard of Undying Pyres
  level: 6.0
  craft: true
  locked: false
- name: Shoulder Straps of Radiance
  level: 4.0
  craft: true
  locked: false
- name: Sol's Spaulders of Courage
  level: 4.0
  craft: true
  locked: false
- name: Spaulders of Enlightenment
  level: 3.0
  craft: true
  locked: false
- name: Spiritual Shoulder Straps
  level: 4.0
  craft: true
  locked: false
- name: Steinbjorn Plackart
  level: 6.0
  craft: true
  locked: false
- name: Surtr's Scorched Cuirass
  level: 7.0
  craft: true
  locked: false
- name: Vidar's Pauldron of Might
  level: 1.0
  craft: true
  locked: false
wrist_pieces:
- name: Berserker Gauntlets
  level: 5.0
  craft: true
  locked: false
- name: Bracers of Enlightenment
  level: 3.0
  craft: true
  locked: false
- name: Bracers of Fallen Stars
  level: 6.0
  craft: true
  locked: false
- name: Bracers of Raven Tears
  level: 3.0
  craft: true
  locked: false
- name: Bracers of Undying Pyres
  level: 6.0
  craft: true
  locked: false
- name: Darkdale Arm Guards
  level: 1.0
  craft: true
  locked: false
- name: Dragon Scaled Bracers
  level: 6.0
  craft: true
  locked: false
- name: Fate Breaker Wraps
  level: 6.0
  craft: true
  locked: false
- name: Fortified Husk Arm Guards
  level: 1.0
  craft: true
  locked: false
- name: Gauntlets of Ares
  level: 7.0
  craft: true
  locked: false
- name: Gauntlets of Guiding Light
  level: 5.0
  craft: true
  locked: false
- name: Gauntlets of Radiance
  level: 4.0
  craft: true
  locked: false
- name: Gauntlets of Zeus
  level: 10.0
  craft: true
  locked: false
- name: Giptumadr's Gauntlets
  level: 5.0
  craft: true
  locked: false
- name: Hunter's Gauntlets
  level: 6.0
  craft: true
  locked: false
- name: Lunda's Lost Bracers
  level: 5.0
  craft: true
  locked: false
- name: Mani's Bracers of Wisdom
  level: 5.0
  craft: true
  locked: false
- name: Nidavellir's Finest Arm Guards
  level: 2.0
  craft: true
  locked: false
- name: Pride of Sparta
  level: 9.1
  craft: true
  locked: false
- name: Risen Snow Gauntlets
  level: 1.0
  craft: true
  locked: false
- name: Sol's Wraps of Courage
  level: 4.0
  craft: true
  locked: false
- name: Spiritual Wraps
  level: 4.0
  craft: true
  locked: false
- name: Steinbjorn Gauntlets
  level: 6.0
  craft: true
  locked: false
- name: Surtr's Scorched Arm
  level: 7.0
  craft: true
  locked: false
- name: Vidar's Bracers of Might
  level: 1.0
  craft: true
  locked: false
- name: Wraps of Survival
  level: 1.0
  craft: true
  locked: false
- name: Wraps of the Black Bear
  level: 1.0
  craft: true
  locked: false
waist_pieces:
- name: Belt of Enlightenment
  level: 3.0
  craft: true
  locked: false
- name: Belt of Radiance
  level: 4.0
  craft: true
  locked: false
- name: Belt of Survival
  level: 1.0
  craft: true
  locked: false
- name: Belt of the Black Bear
  level: 1.0
  craft: true
  locked: false
- name: Berserker Waist Guard
  level: 5.0
  craft: true
  locked: false
- name: Darkdale Waist Guard
  level: 1.0
  craft: true
  locked: false
- name: Dragon Scaled Girdle
  level: 6.0
  craft: true
  locked: false
- name: Fate Breaker Belt
  level: 6.0
  craft: true
  locked: false
- name: Fortified Husk Girdle
  level: 1.0
  craft: true
  locked: false
- name: Giptumadr's Waist Guard
  level: 5.0
  craft: true
  locked: false
- name: Girdle of Raven Tears
  level: 3.0
  craft: true
  locked: false
- name: Girdle of Undying Pyres
  level: 6.0
  craft: true
  locked: false
- name: Hunter's Belt
  level: 6.0
  craft: true
  locked: false
- name: Lunda's Lost Belt
  level: 5.0
  craft: true
  locked: false
- name: Mani's Belt of Wisdom
  level: 5.0
  craft: true
  locked: false
- name: Mark of Sparta
  level: 9.1
  craft: true
  locked: false
- name: Nidavellir's Finest Waist Guard
  level: 2.0
  craft: true
  locked: false
- name: Risen Snow Girdle
  level: 1.0
  craft: true
  locked: false
- name: Sol's Belt of Courage
  level: 4.0
  craft: true
  locked: false
- name: Spiritual Belt
  level: 4.0
  craft: true
  locked: false
- name: Steinbjorn Waist Guard
  level: 6.0
  craft: true
  locked: false
- name: Surtr's Scorched Girdle
  level: 7.0
  craft: true
  locked: false
- name: Vidar's Belt of Might
  level: 1.0
  craft: true
  locked: false
- name: Waist Guard of Fallen Stars
  level: 6.0
  craft: true
  locked: false
- name: Waist Guard of Guiding Light
  level: 5.0
  craft: true
  locked: false
- name: War Belt of Ares
  level: 7.0
  craft: true
  locked: false
- name: War Belt of Zeus
  level: 10.0
  craft: true
  locked: false
axe_attachments:
- name: Banahogg Knob
  level: 6.0
  craft: true
  locked: false
- name: Fortified Frost Knob
  level: 2.0
  craft: true
  locked: false
- name: Grip of Darkdale
  level: 1.0
  craft: true
  locked: false
- name: Grip of Healing Harmony
  level: 5.0
  craft: true
  locked: false
- name: Grip of Radiant Reflection
  level: 6.0
  craft: true
  locked: false
- name: Grip of Weighted Recovery
  level: 4.0
  craft: true
  locked: false
- name: Grip of the Fallen Alchemist
  level: 5.0
  craft: true
  locked: false
- name: Haur's Lucky Knob
  level: 2.0
  craft: true
  locked: false
- name: Runic Hailstone Knob
  level: 6.0
  craft: true
  locked: false
- name: Stonecutter's Knob
  level: 4.0
  craft: true
  locked: false
- name: The Furious Maul
  level: 1.0
  craft: true
  locked: false
- name: Wooden Knob
  level: 2.0
  craft: true
  locked: false
blades_attachments:
- name: Cursed Empress Handles
  level: 2.0
  craft: true
  locked: false
- name: Darkdale Handles
  level: 1.0
  craft: true
  locked: false
- name: Deadly Obsidian Handles
  level: 1.0
  craft: true
  locked: false
- name: Hardened War Handles
  level: 5.0
  craft: true
  locked: false
- name: Luminous Recovery Handles
  level: 6.0
  craft: true
  locked: false
- name: Pommels of Agile Deceit
  level: 4.0
  craft: true
  locked: false
- name: Pommels of Brutal Might
  level: 4.0
  craft: true
  locked: false
- name: Pommels of Burning Unity
  level: 6.0
  craft: true
  locked: false
- name: Pommels of the True Flame
  level: 6.0
  craft: true
  locked: false
- name: Pommels of the Undying Spark
  level: 2.0
  craft: true
  locked: false
- name: Radiant Warden Handles
  level: 2.0
  craft: true
  locked: false
- name: Steel Handles
  level: 1.0
  craft: true
  locked: false
spear_attachments:
- name: Battle-Scarred Sauroter
  level: 6.0
  craft: true
  locked: false
- name: Charging Assault Sauroter
  level: 5.0
  craft: true
  locked: false
- name: Hind of Attuned Elements
  level: 5.0
  craft: true
  locked: false
- name: Hind of Volatile Might
  level: 6.0
  craft: true
  locked: false
- name: Hind of Weightless Recovery
  level: 6.0
  craft: true
  locked: false
- name: Hind of the Four Winds
  level: 5.0
  craft: true
  locked: false
- name: Lion's Roar Sauroter
  level: 5.0
  craft: true
  locked: false
- name: Mighty Olympic Sauroter
  level: 5.0
  craft: true
  locked: false
- name: Soldier's Sauroter
  level: 4.0
  craft: true
  locked: false
- name: Warrior's Echo Sauroter
  level: 6.0
  craft: true
  locked: false
shield_attachments:
- name: Rond of Absorption
  level: 6.0
  craft: true
  locked: false
- name: Rond of Affliction
  level: 3.0
  craft: true
  locked: false
- name: Rond of Aggravation
  level: 2.0
  craft: true
  locked: false
- name: Rond of Deflection
  level: 5.0
  craft: true
  locked: false
- name: Rond of Disruption
  level: 7.0
  craft: true
  locked: false
- name: Rond of Expedition
  level: 3.0
  craft: true
  locked: false
- name: Rond of Fortification
  level: 6.0
  craft: true
  locked: false
- name: Rond of Obliteration
  level: 8.0
  craft: true
  locked: false
- name: Rond of Purification
  level: 5.0
  craft: true
  locked: false
- name: Rond of Restoration
  level: 4.0
  craft: true
  locked: false
- name: Rond of Volition
  level: 1.0
  craft: true
  locked: false
- name: Rond of the Nine Realms
  level: 6.0
  craft: true
  locked: false
resource_budget:
  Hacksilver: 0
optimization_stats:
- Strength
- Defense
- Runic
- Vitality
- Cooldown
- Luck
stat_presets:
  Defensive:
  - Defense
  - Vitality
  Aggressive:
  - Strength
  - Runic
  Balanced:
  - Strength
  - Defense
  - Runic
  - Vitality
