force_scrape: false
armor_csv: data/all_pieces.csv
weapons_csv: data/all_weapons.csv
mat_aliases:
  Smouldering Embers: Smoldering Embers
  Petrified Bones: Petrified Bone
  Whispering Slabs: Whispering Slab
  Asgardian Ingots: Asgardian Ingot
  Dwaren Steel: Dwarven Steel
  s Broken Cuirass: Lunda's Broken Cuirass
  s Broken Bracers: Lunda's Broken Bracers
  s Broken Belt: Lunda's Broken Belt
chest_pieces:
- name: Lunda's Lost Cuirass
  level: 5
  craft: true
- name: Spiritual Shoulder Straps
  level: 4
  craft: true
- name: Sol's Spaulders of Courage
  level: 4
  craft: false
- name: Spaulders of Enlightenment
  level: 3
  craft: true
- name: Fortified Husk Cuirass
  level: 3
  craft: true
- name: Nidavellir's Finest Plackart
  level: 2
  craft: true
- name: Cloak of the Black Bear
  level: 2
  craft: false
- name: Vidar's Pauldron of Might
  level: 1
  craft: true
- name: Shoulder Guard of Survival
  level: 1
  craft: false
- name: Spiritual Shoulder Straps
  level: 4
  craft: false
wrist_pieces:
- name: Sol's Wraps of Courage
  level: 4
  craft: true
- name: Gauntlets of Radiance
  level: 4
  craft: true
- name: Spiritual Wraps
  level: 5
  craft: false
- name: Bracers of Enlightenment
  level: 3
  craft: true
- name: Wraps of the Black Bear
  level: 3
  craft: false
- name: Nidavellir's Finest Arm Guards
  level: 2
  craft: true
- name: Vidar's Bracers of Might
  level: 1
  craft: true
- name: Fortified Husk Arm Guards
  level: 1
  craft: true
- name: Wraps of Survival
  level: 1
  craft: false
waist_pieces:
- name: Lunda's Lost Belt
  level: 5
  craft: true
- name: Sol's Belt of Courage
  level: 4
  craft: true
- name: Belt of Radiance
  level: 4
  craft: false
- name: Spiritual Belt
  level: 5
  craft: false
- name: Belt of Enlightenment
  level: 3
  craft: true
- name: Belt of the Black Bear
  level: 3
  craft: false
- name: Nidavellir's Finest Waist Guard
  level: 2
  craft: true
- name: Vidar's Belt of Might
  level: 1
  craft: true
- name: Fortified Husk Girdle
  level: 1
  craft: true
- name: Belt of Survival
  level: 1
  craft: false
axe_attachments:
- name: Grip of the Fallen Alchemist
  level: 5
  craft: false
- name: Grip of Weighted Recovery
  level: 4
  craft: true
- name: Stonecutter's Knob
  level: 4
  craft: false
- name: Haur's Lucky Knob
  level: 3
  craft: false
- name: Wooden Knob
  level: 3
  craft: false
- name: The Furious Maul
  level: 2
  craft: true
blades_attachments:
- name: Hardened War Handles
  level: 5
  craft: false
- name: Pommels of Brutal Might
  level: 4
  craft: true
- name: Pommels of Agile Deceit
  level: 4
  craft: false
- name: Steel Handles
  level: 4
  craft: false
- name: Radiant Warden Handles
  level: 3
  craft: false
- name: Cursed Empress Handles
  level: 2
  craft: false
spear_attachments: []
shield_attachments:
- name: Rond of Affliction
  level: 5
  craft: false
- name: Rond of Expedition
  level: 3
  craft: false
- name: Rond of Volition
  level: 1
  craft: false
- name: Rond of Aggravation
  level: 2
  craft: false
resource_budget:
  Asgardian Ingot: 1
  Blazing Embers: 0
  Bonded Leather: 35
  Celestial Fossil: 0
  Divine Ashes: 0
  Dragon Claw: 0
  Dragon Tooth: 4
  Dust of Realms: 5
  Dwarven Steel: 15
  Essence of Hel: 0
  Forged Iron: 68
  Forsaken Breath: 0
  Fortified Remnants: 0
  Gleaming Crystal: 0
  Glowing Embers: 0
  Hacksilver: 78010
  Hardened Remnants: 0
  Honed Metal: 14
  Lindwyrm Scales: 0
  Luminous Alloy: 0
  Lunda's Broken Belt: 0
  Lunda's Broken Bracers: 0
  Lunda's Broken Cuirass: 0
  Mountain Root: 0
  Nidavellir Ore: 6
  Petrified Bone: 0
  Purified Crystalline: 0
  Rawhide: 48
  Shining Crystal: 0
  Skap Slag: 0
  Slag Deposits: 35
  Smoldering Embers: 0
  Sovereign Coals: 0
  Sparkling Crystal: 0
  Stonewood: 14
  Tempered Remnants: 0
  Whispering Slab: 62
