force_scrape: false
armor_csv: data/all_pieces.csv
weapons_csv: data/all_weapons.csv
mat_aliases:
  Smouldering Embers: Smoldering Embers
  Petrified Bones: Petrified Bone
  Whispering Slabs: Whispering Slab
  Asgardian Ingots: Asgardian Ingot
  Dwaren Steel: Dwarven Steel
  s Broken Cuirass: Lunda's Broken Cuirass
  s Broken Bracers: Lunda's Broken Bracers
  s Broken Belt: Lunda's Broken Belt
chest_pieces:
- craft: false
  level: 5
  name: Lunda's Lost Cuirass
- craft: false
  level: 5
  name: Spiritual Shoulder Straps
- craft: false
  level: 4
  name: Sol's Spaulders of Courage
- craft: true
  level: 3
  name: Spaulders of Enlightenment
- craft: true
  level: 3
  name: Fortified Husk Cuirass
- craft: true
  level: 2
  name: Nidavellir's Finest Plackart
- craft: false
  level: 2
  name: Cloak of the Black Bear
- craft: true
  level: 1
  name: Vidar's Pauldron of Might
- craft: false
  level: 1
  name: Shoulder Guard of Survival
- craft: false
  level: 5
  name: Giptumadr's Breastplate
- craft: false
  level: 5
  name: Breastplate of Guiding Light
wrist_pieces:
- craft: true
  level: 4
  name: Sol's Wraps of Courage
- craft: false
  level: 4
  name: Gauntlets of Radiance
- craft: false
  level: 6
  name: Spiritual Wraps
- craft: true
  level: 3
  name: Bracers of Enlightenment
- craft: false
  level: 3
  name: Wraps of the Black Bear
- craft: true
  level: 2
  name: Nidavellir's Finest Arm Guards
- craft: true
  level: 1
  name: Vidar's Bracers of Might
- craft: true
  level: 1
  name: Fortified Husk Arm Guards
- craft: false
  level: 1
  name: Wraps of Survival
- craft: false
  level: 5
  name: Gauntlets of Guiding Light
waist_pieces:
- craft: false
  level: 6
  name: Lunda's Lost Belt
- craft: true
  level: 4
  name: Sol's Belt of Courage
- craft: false
  level: 4
  name: Belt of Radiance
- craft: false
  level: 5
  name: Spiritual Belt
- craft: true
  level: 3
  name: Belt of Enlightenment
- craft: false
  level: 3
  name: Belt of the Black Bear
- craft: true
  level: 2
  name: Nidavellir's Finest Waist Guard
- craft: true
  level: 1
  name: Vidar's Belt of Might
- craft: true
  level: 1
  name: Fortified Husk Girdle
- craft: false
  level: 1
  name: Belt of Survival
- craft: false
  level: 5
  name: Waist Guard of Guiding Light
- craft: false
  level: 3
  name: Girdle of Raven Tears
axe_attachments:
- craft: false
  level: 5
  name: Grip of the Fallen Alchemist
- craft: true
  level: 4
  name: Grip of Weighted Recovery
- craft: false
  level: 4
  name: Stonecutter's Knob
- craft: false
  level: 3
  name: Haur's Lucky Knob
- craft: false
  level: 3
  name: Wooden Knob
- craft: true
  level: 2
  name: The Furious Maul
blades_attachments:
- craft: false
  level: 6
  name: Hardened War Handles
- craft: true
  level: 4
  name: Pommels of Brutal Might
- craft: false
  level: 4
  name: Pommels of Agile Deceit
- craft: false
  level: 4
  name: Steel Handles
- craft: false
  level: 3
  name: Radiant Warden Handles
- craft: false
  level: 2
  name: Cursed Empress Handles
spear_attachments: []
shield_attachments:
- craft: false
  level: 6
  name: Rond of Affliction
- craft: false
  level: 3
  name: Rond of Expedition
- craft: false
  level: 1
  name: Rond of Volition
- craft: false
  level: 2
  name: Rond of Aggravation
- craft: false
  level: 5
  name: Rond of Purification
resource_budget:
  Asgardian Ingot: 0
  Blazing Embers: 0
  Bonded Leather: 120
  Celestial Fossil: 0
  Divine Ashes: 0
  Dragon Claw: 1
  Dragon Tooth: 14
  Dust of Realms: 25
  Dwarven Steel: 46
  Essence of Hel: 0
  Forged Iron: 114
  Forsaken Breath: 0
  Fortified Remnants: 0
  Gleaming Crystal: 0
  Glowing Embers: 0
  Hacksilver: 2194
  Hardened Remnants: 0
  Honed Metal: 30
  Lindwyrm Scales: 0
  Luminous Alloy: 0
  Lunda's Broken Belt: 0
  Lunda's Broken Bracers: 1
  Lunda's Broken Cuirass: 0
  Mountain Root: 0
  Nidavellir Ore: 6
  Petrified Bone: 1
  Purified Crystalline: 0
  Rawhide: 100
  Shining Crystal: 0
  Skap Slag: 0
  Slag Deposits: 65
  Smoldering Embers: 0
  Sovereign Coals: 4
  Sparkling Crystal: 0
  Stonewood: 43
  Tempered Remnants: 0
  Whispering Slab: 221
optimization_stats:
- Strength
- Defense
- Runic
- Vitality
- Cooldown
- Luck
stat_presets:
  Defensive:
  - Defense
  - Vitality
  Aggressive:
  - Strength
  - Runic
  Balanced:
  - Strength
  - Defense
  - Runic
  - Vitality
